# Training configuration
data:
  train_path: ".\\datasets\\training"
  val_path: ".\\datasets\\validation"
  batch_size: 32
  num_workers: 4

model:
  name: 'densenet121'  # 'densenet121'   "resnet50", "vgg16",
  pretrained: True
  num_classes: 5

training:
  epochs: 100
  learning_rate: 0.0001
  weight_decay: 0.9999
  lr_patience: 5  # for LR schedular
  factor: 0.5  # for LR schedular
  early_stop: True
  es_patience: 100  # Wait 10 epochs without improvement
  delta: 0.001  # Requires at least 0.001 improvement in validation accuracy

paths:
  model_save_dir: "./saved_models"
  log_dir: "./logs"
